:compat-mode:
= Lab 6 - Blue/Green Deployments

[abstract]
--
Using a blue/green deployment technique, zero-downtime upgrades for your applications are possible with PCF.

By applying the same route to multiple versions of the application, the GoRouter will automatically balance traffic between the different versions. Once the older version is removed, all users will directed to new version with no interruption of applicaiton usage. 
--
. Change to the Blue Green Deployment lab directory:
+
----
cd $COURSE_HOME/Labs/Lab06-Blue_Green_Deployment
----
. Examine the manifest.yml file in the directory and note that it will push 2 different "Hellow World" php applications, hello-v1 and hello-v2.  Once you finish reviewing, push the applications using the below command:
+
----
$ cf push 
----
. Use the CLI to verify that you now have two different applications with three different routes.  Two routes will point to hello-v1 and one route to hello-v2.
+
----
$ cf routes
----
+
. In a browser, access your version 2 application on its unique route.
Let's assume your application is stable and we are ready to move all traffic on the v1 route to the v2 application.
. Map the v1 route on your v2 app to point to the route on the v1 app. `DOMAIN` refers to the portion of the route specific to PWS. 
+
----
$ cf map-route V2_APP_NAME DOMAIN -h V1_HOSTNAME
----
+
. Refresh your browser a few times using the original route. Notice that both versions are sometimes displayed.
. Unmap the route to the version 1 application.
+
----
$ cf unmap-route V1_APP_NAME DOMAIN -h V1_HOSTNAME
----
+
Now on the original route, you should only see version 2 of the application. The end users never experienced any downtime.
`Optional` You are now free to unmap v2 route and delete v1 app.
